# Use root/example as user/password credentials
version: '2.1'

services:

  warden_db:
    container_name: warden-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warden
      MYSQL_USER: warden_admin
      MYSQL_PASSWORD: warden@123!bB
    ports:
      - "3307:3306"
    networks:
      - api_network
    expose:
    # Opens port 3306 on the container
    - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  warden:
    container_name: warden
    image: drumer2142/warden:0.0.1
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    volumes:
    - ./src/:/go/src/warden
    ports:
      - "8888:8888"
    networks:
      - api_network
    depends_on:
      db:
        condition: service_healthy
    #for v3+ use wait-for-it
    #commmand: ["./wait-for-it.sh", "db:3306", "--", "go", "run", "src/*.go"]

networks:
  api_network:
    driver: bridge
